spring:
  profiles:
    include: security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qrcode?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "043098"
  session:
    store-type: none
security:
  basic:
    enabled: true
server:
  port: 8080
